// Generated by gencpp from file waterplus_map_tools/GetWaypointByName.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_GETWAYPOINTBYNAME_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_GETWAYPOINTBYNAME_H

#include <ros/service_traits.h>


#include "GetWaypointByNameRequest.h"
#include "GetWaypointByNameResponse.h"


namespace waterplus_map_tools
{

struct GetWaypointByName
{

typedef GetWaypointByNameRequest Request;
typedef GetWaypointByNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypointByName
} // namespace waterplus_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waterplus_map_tools::GetWaypointByName > {
  static const char* value()
  {
    return "5164dc1f215ac8183cbe49b46c7ff40e";
  }

  static const char* value(const ::waterplus_map_tools::GetWaypointByName&) { return value(); }
};

template<>
struct DataType< ::waterplus_map_tools::GetWaypointByName > {
  static const char* value()
  {
    return "waterplus_map_tools/GetWaypointByName";
  }

  static const char* value(const ::waterplus_map_tools::GetWaypointByName&) { return value(); }
};


// service_traits::MD5Sum< ::waterplus_map_tools::GetWaypointByNameRequest> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::GetWaypointByName > 
template<>
struct MD5Sum< ::waterplus_map_tools::GetWaypointByNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::GetWaypointByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetWaypointByNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::GetWaypointByNameRequest> should match 
// service_traits::DataType< ::waterplus_map_tools::GetWaypointByName > 
template<>
struct DataType< ::waterplus_map_tools::GetWaypointByNameRequest>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::GetWaypointByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetWaypointByNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waterplus_map_tools::GetWaypointByNameResponse> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::GetWaypointByName > 
template<>
struct MD5Sum< ::waterplus_map_tools::GetWaypointByNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::GetWaypointByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetWaypointByNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::GetWaypointByNameResponse> should match 
// service_traits::DataType< ::waterplus_map_tools::GetWaypointByName > 
template<>
struct DataType< ::waterplus_map_tools::GetWaypointByNameResponse>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::GetWaypointByName >::value();
  }
  static const char* value(const ::waterplus_map_tools::GetWaypointByNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_GETWAYPOINTBYNAME_H
