// Generated by gencpp from file wpb_home_behaviors/Rect.msg
// DO NOT EDIT!


#ifndef WPB_HOME_BEHAVIORS_MESSAGE_RECT_H
#define WPB_HOME_BEHAVIORS_MESSAGE_RECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wpb_home_behaviors
{
template <class ContainerAllocator>
struct Rect_
{
  typedef Rect_<ContainerAllocator> Type;

  Rect_()
    : name()
    , top()
    , bottom()
    , left()
    , right()
    , probability()  {
    }
  Rect_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , top(_alloc)
    , bottom(_alloc)
    , left(_alloc)
    , right(_alloc)
    , probability(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _top_type;
  _top_type top;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _bottom_type;
  _bottom_type bottom;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _left_type;
  _left_type left;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _right_type;
  _right_type right;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _probability_type;
  _probability_type probability;





  typedef boost::shared_ptr< ::wpb_home_behaviors::Rect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wpb_home_behaviors::Rect_<ContainerAllocator> const> ConstPtr;

}; // struct Rect_

typedef ::wpb_home_behaviors::Rect_<std::allocator<void> > Rect;

typedef boost::shared_ptr< ::wpb_home_behaviors::Rect > RectPtr;
typedef boost::shared_ptr< ::wpb_home_behaviors::Rect const> RectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wpb_home_behaviors::Rect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wpb_home_behaviors::Rect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wpb_home_behaviors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wpb_home_behaviors': ['/home/yue/demo/src/wpb_home/wpb_home_behaviors/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wpb_home_behaviors::Rect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wpb_home_behaviors::Rect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wpb_home_behaviors::Rect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2e8cef4f7bbfddf42bb42bcc97ae935";
  }

  static const char* value(const ::wpb_home_behaviors::Rect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2e8cef4f7bbfddfULL;
  static const uint64_t static_value2 = 0x42bb42bcc97ae935ULL;
};

template<class ContainerAllocator>
struct DataType< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wpb_home_behaviors/Rect";
  }

  static const char* value(const ::wpb_home_behaviors::Rect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n\
int32[] top\n\
int32[] bottom\n\
int32[] left\n\
int32[] right\n\
float64[] probability\n\
";
  }

  static const char* value(const ::wpb_home_behaviors::Rect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.top);
      stream.next(m.bottom);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wpb_home_behaviors::Rect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wpb_home_behaviors::Rect_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "top[]" << std::endl;
    for (size_t i = 0; i < v.top.size(); ++i)
    {
      s << indent << "  top[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.top[i]);
    }
    s << indent << "bottom[]" << std::endl;
    for (size_t i = 0; i < v.bottom.size(); ++i)
    {
      s << indent << "  bottom[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bottom[i]);
    }
    s << indent << "left[]" << std::endl;
    for (size_t i = 0; i < v.left.size(); ++i)
    {
      s << indent << "  left[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.left[i]);
    }
    s << indent << "right[]" << std::endl;
    for (size_t i = 0; i < v.right.size(); ++i)
    {
      s << indent << "  right[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.right[i]);
    }
    s << indent << "probability[]" << std::endl;
    for (size_t i = 0; i < v.probability.size(); ++i)
    {
      s << indent << "  probability[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.probability[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WPB_HOME_BEHAVIORS_MESSAGE_RECT_H
