// Generated by gencpp from file wpb_home_tutorials/Follow.msg
// DO NOT EDIT!


#ifndef WPB_HOME_TUTORIALS_MESSAGE_FOLLOW_H
#define WPB_HOME_TUTORIALS_MESSAGE_FOLLOW_H

#include <ros/service_traits.h>


#include <wpb_home_tutorials/FollowRequest.h>
#include <wpb_home_tutorials/FollowResponse.h>


namespace wpb_home_tutorials
{

struct Follow
{

typedef FollowRequest Request;
typedef FollowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Follow
} // namespace wpb_home_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wpb_home_tutorials::Follow > {
  static const char* value()
  {
    return "24fe904d75d710a2e0b16246fbf996c5";
  }

  static const char* value(const ::wpb_home_tutorials::Follow&) { return value(); }
};

template<>
struct DataType< ::wpb_home_tutorials::Follow > {
  static const char* value()
  {
    return "wpb_home_tutorials/Follow";
  }

  static const char* value(const ::wpb_home_tutorials::Follow&) { return value(); }
};


// service_traits::MD5Sum< ::wpb_home_tutorials::FollowRequest> should match 
// service_traits::MD5Sum< ::wpb_home_tutorials::Follow > 
template<>
struct MD5Sum< ::wpb_home_tutorials::FollowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wpb_home_tutorials::Follow >::value();
  }
  static const char* value(const ::wpb_home_tutorials::FollowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpb_home_tutorials::FollowRequest> should match 
// service_traits::DataType< ::wpb_home_tutorials::Follow > 
template<>
struct DataType< ::wpb_home_tutorials::FollowRequest>
{
  static const char* value()
  {
    return DataType< ::wpb_home_tutorials::Follow >::value();
  }
  static const char* value(const ::wpb_home_tutorials::FollowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wpb_home_tutorials::FollowResponse> should match 
// service_traits::MD5Sum< ::wpb_home_tutorials::Follow > 
template<>
struct MD5Sum< ::wpb_home_tutorials::FollowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wpb_home_tutorials::Follow >::value();
  }
  static const char* value(const ::wpb_home_tutorials::FollowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wpb_home_tutorials::FollowResponse> should match 
// service_traits::DataType< ::wpb_home_tutorials::Follow > 
template<>
struct DataType< ::wpb_home_tutorials::FollowResponse>
{
  static const char* value()
  {
    return DataType< ::wpb_home_tutorials::Follow >::value();
  }
  static const char* value(const ::wpb_home_tutorials::FollowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WPB_HOME_TUTORIALS_MESSAGE_FOLLOW_H
